# Generated by Django 5.2.8 on 2025-12-03 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author_name', models.CharField(max_length=255, verbose_name='Autor')),
                ('cover_image', models.ImageField(upload_to='audiobooks/covers/', verbose_name='Portada')),
                ('audio_file', models.FileField(upload_to='audiobooks/audio/', verbose_name='Archivo de audio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
        ),
    ]
