# Generated by Django 5.2.8 on 2025-12-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Texto de la pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Audiobooks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='audiobooks.audiobook', verbose_name='Audiolibro')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Texto de la opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Correcta?')),
                ('points_if_correct', models.IntegerField(default=1, verbose_name='Puntos si es correcta')),
                ('points_if_wrong', models.IntegerField(default=0, verbose_name='Puntos si es incorrecta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='audiobooks.questions', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
            },
        ),
    ]
