# Generated by Django 5.2.8 on 2025-12-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_questions_answeroption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Audiobooks',
            new_name='audiobooks',
        ),
    ]
