# Generated by Django 5.2.8 on 2025-12-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0003_rename_audiobooks_questions_audiobooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('puntaje', models.FloatField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.audiobook')),
            ],
        ),
    ]
