# Generated by Django 5.2.8 on 2025-12-09 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0004_resultadocuestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100, verbose_name='Palabra')),
                ('definicion', models.TextField(verbose_name='Definición')),
                ('ejemplo', models.TextField(blank=True, null=True, verbose_name='Ejemplo de uso')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario', to='audiobooks.audiobook', verbose_name='Audiolibro')),
            ],
            options={
                'verbose_name': 'Vocabulario',
                'verbose_name_plural': 'Vocabularios',
            },
        ),
    ]
