# Generated by Django 5.2.6 on 2025-12-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0005_vocabulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justificación de la respuesta'),
        ),
    ]
