# Generated by Django 5.2.8 on 2025-12-29 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0006_answeroption_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobooks/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF (Libro)'),
        ),
    ]
