# Generated by Django 5.2.8 on 2026-01-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0007_audiobook_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
