# Generated by Django 5.2.8 on 2026-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0008_audiobook_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
