# Generated by Django 5.2.8 on 2026-01-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0009_audiobook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
