# Generated by Django 5.2.8 on 2026-01-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0010_alter_audiobook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
    ]
