# Generated by Django 5.2.8 on 2026-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0011_alter_questions_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadocuestionario',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
